// Generated by CoffeeScript 1.3.1
(function() {
  var _base, _base1, _base2;

  (_base = String.prototype).explode || (_base.explode = function() {
    return this.split(/[,\s]+/g);
  });

  (_base1 = Date.prototype).toShortDateString || (_base1.toShortDateString = function() {
    return this.toDateString().replace(/^[^\s]+\s/, '');
  });

  (_base2 = Date.prototype).toISODateString || (_base2.toISODateString = Date.prototype.toISOString);

}).call(this);
