// Generated by CoffeeScript 1.3.1
(function() {
  var Collection, FileCollection, balUtil, fsUtil, pathUtil, _,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor; child.__super__ = parent.prototype; return child; };

  pathUtil = require('path');

  fsUtil = require('fs');

  balUtil = require('bal-util');

  _ = require('underscore');

  Collection = require(__dirname + '/../base').Collection;

  FileCollection = (function(_super) {

    __extends(FileCollection, _super);

    FileCollection.name = 'FileCollection';

    function FileCollection() {
      return FileCollection.__super__.constructor.apply(this, arguments);
    }

    return FileCollection;

  })(Collection);

}).call(this);
