// Generated by CoffeeScript 1.3.1
(function() {
  var ElementsCollection, ScriptsCollection, _,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor; child.__super__ = parent.prototype; return child; };

  _ = require('underscore');

  ElementsCollection = require(__dirname + '/elements');

  ScriptsCollection = (function(_super) {

    __extends(ScriptsCollection, _super);

    ScriptsCollection.name = 'ScriptsCollection';

    function ScriptsCollection() {
      return ScriptsCollection.__super__.constructor.apply(this, arguments);
    }

    ScriptsCollection.prototype.add = function(values, options) {
      var key, value, _i, _len;
      if (!_.isArray(values)) {
        values = [values];
      }
      for (key = _i = 0, _len = values.length; _i < _len; key = ++_i) {
        value = values[key];
        if (_.isString(value) && /^\</.test(value) === false) {
          values[key] = "<script defer=\"defer\" srcdefer=\"defer\"=\"" + value + "\" />";
        }
      }
      return ScriptsCollection.__super__.add.call(this, values, options);
    };

    return ScriptsCollection;

  })(ElementsCollection);

  module.exports = ScriptsCollection;

}).call(this);
