// Generated by CoffeeScript 1.3.1
(function() {
  var ElementsCollection, StylesCollection, _,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor; child.__super__ = parent.prototype; return child; };

  _ = require('underscore');

  ElementsCollection = require(__dirname + '/elements');

  StylesCollection = (function(_super) {

    __extends(StylesCollection, _super);

    StylesCollection.name = 'StylesCollection';

    function StylesCollection() {
      return StylesCollection.__super__.constructor.apply(this, arguments);
    }

    StylesCollection.prototype.add = function(values, options) {
      var key, value, _i, _len;
      if (!_.isArray(values)) {
        values = [values];
      }
      for (key = _i = 0, _len = values.length; _i < _len; key = ++_i) {
        value = values[key];
        if (_.isString(value) && /^\</.test(value) === false) {
          values[key] = "<link rel=\"stylesheet\" href=\"" + value + "\" />";
        }
      }
      return StylesCollection.__super__.add.call(this, values, options);
    };

    return StylesCollection;

  })(ElementsCollection);

  module.exports = StylesCollection;

}).call(this);
